Add word of the day section
narbs91/glosseta pull request #158
Opened 2022-04-12 18:04 UTC by alireza-jahandoost

### What does this PR do?
Add "Word of the day" section to index page

### Any helpful background information around the changes?

### Any new dependencies? Why were they added?
No

### Relevant Screenshots/gifs

### Does is close any issue(s)?
[issue #157](https://github.com/narbs91/glosseta/issues/157)

Closes # ...

2022-04-13 04:00 UTC, narbs91 commented
Hi @alireza-jahandoost thank you so much for the prompt work on this issue!  It looks like you are getting some build issues with the page on build you can observe the output [here](https://github.com/narbs91/glosseta/runs/6001325348?check_suite_focus=true) or look to reproduce it via `yarn build` on your machine.

2022-04-13 09:45 UTC, alireza-jahandoost commented
@narbs91 The problem solved with moving new component to src/components directory. I think we have to move other components from src/pages directory to this directory. Should I open an issue about it?

2022-04-14 05:12 UTC, narbs91 commented
Hi @alireza-jahandoost moving it outside the pages folder seems kinda odd for it to be the fix.  I'll have a closer look in the upcoming days as well as a review of the UI (from my original design proposal) and let you know.  Thank you for the great work 🚀

2022-04-14 07:26 UTC, alireza-jahandoost commented
Hi @narbs91 . If you reset the HEAD to the point that it has error, and try to build, a link to the cause of error is [this](https://nextjs.org/docs/messages/prerender-error). And the recommended way to solve it is to move every non-pages to out of `page` directory.

2022-04-17 04:30 UTC, narbs91 requested changes
Overall looks great!  Just a few minor tweaks and we should be good to go

2022-04-18 09:15 UTC, alireza-jahandoost commented on src/components/daily-word/daily-word.tsx
> +import React from 'react';
Yes, of course.

2022-04-19 04:43 UTC, narbs91 approved these changes
LGTM!  Awesome work here and really appreciate you stepping up to do this, i think people are really going like this feature :).  I'll get this merged in the morning tomorrow!

2022-04-19 04:45 UTC, narbs91 commented
@all-contributors please add @alireza-jahandoost for code

2022-04-19 15:19 UTC, merged